apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app2-deployment
spec:
  replicas: 1  # You can increase this number for more instances
  selector:
    matchLabels:
      app: flask-app2
  template:
    metadata:
      labels:
        app: flask-app2
    spec:
      containers:
      - name: flask-app2
        image: flask-app2  # This is your Docker image name
        ports:
        - containerPort: 8999  # Port on which Flask app will run inside the container
